# Pytorch Komponenten

In [2]:
import torch
import torch.nn as nn

x = torch.rand(8)
x

tensor([0.2130, 0.8128, 0.9764, 0.9008, 0.6059, 0.6593, 0.1250, 0.5652])

### Beispiel

Erzeugen einer linear layer:

In [3]:
m = nn.Linear(8, 1) # 8 features[Input], ein Output !
m(x)

tensor([-0.0429], grad_fn=<AddBackward0>)

### Aufgabe 1

Erzeuge eine linear layer und führe ein forwarding wie im Beispiel durch mit: 
- in_features=8
- out_features=16

In [4]:
class Net(nn.Module): # Vererbung, daher Quelle in die Klammern
    
    def __init__(self):
        super().__init__()# gibt die Superklasse nn.module, außerdem rufen wir den Constuctor dieser Klasse auf!
        self.l1 = nn.Linear(8, 16)
        
    def forward(self, x):
        x = self.l1(x)# wir überschreiben x mit dem Ergebnis aus Layer1
        return x
model = Net() # wir erzeugen ein Objekt der Klasse ! und packen es in eine variable (model)
model

Net(
  (l1): Linear(in_features=8, out_features=16, bias=True)
)

In [6]:
# falsch, 1. zu viel 2. nicht geforwarded

m = nn.Linear(8, 16)
m(x)

tensor([-0.1864, -0.9193, -0.2943,  0.7199, -0.4111,  0.6331,  0.1186,  1.1646,
        -0.5898,  0.6508, -0.5831, -0.2813, -0.4347,  0.5954,  0.3560, -0.4958],
       grad_fn=<AddBackward0>)

### Aufgabe 2

Erzeuge eine ReLU activation function und führe ein forwarding wie im Beispiel durch.

In [4]:
class Net(nn.Module): # Vererbung, daher Quelle in die Klammern
    
    def __init__(self):
        super().__init__()# gibt die Superklasse nn.module, außerdem rufen wir den Constuctor dieser Klasse auf!
        self.l1 = nn.Linear(8, 16)
        self.g = nn.ReLU()
        
    def forward(self, x):
        x = self.l1(x)# wir überschreiben x mit dem Ergebnis aus Layer1
        x = self.g(x) # Pro Layer eine ReLU üblicherweise !
        return x
    
model = Net() # wir erzeugen ein Objekt der Klasse ! und packen es in eine variable (model)
model

Net(
  (l1): Linear(in_features=8, out_features=16, bias=True)
  (g): ReLU()
)

In [7]:
# falsch, 1. zu viel 2. nicht geforwarded

m = nn.ReLU()
m(x)

tensor([0.2130, 0.8128, 0.9764, 0.9008, 0.6059, 0.6593, 0.1250, 0.5652])

### Aufgabe 3

Erzeuge eine Dropout layer und führe ein forwarding wie im Beispiel durch.
- propability für den Dropout 30%

In [5]:
class Net(nn.Module): # Vererbung, daher Quelle in die Klammern
    
    def __init__(self):
        super().__init__()# gibt die Superklasse nn.module, außerdem rufen wir den Constuctor dieser Klasse auf!
        self.l1 = nn.Linear(8, 16)
        self.g = nn.ReLU()
        self.d = nn.Dropout(p=0.3, inplace=False)# Vermutung, inplace kann man analog der Libary übernehmen oder weglasssen (default value)
        
    def forward(self, x):
        x = self.l1(x)# wir überschreiben x mit dem Ergebnis aus Layer1
        x = self.g(x) # Pro Layer eine ReLU üblicherweise !
        x = self.d(x)
        return x
    
        
model = Net() # wir erzeugen ein Objekt der Klasse ! und packen es in eine variable (model)
model

Net(
  (l1): Linear(in_features=8, out_features=16, bias=True)
  (g): ReLU()
  (d): Dropout(p=0.3, inplace=False)
)

In [8]:
# falsch, 1. zu viel 2. nicht geforwarded

m = nn.Dropout(p=0.3)
m(x)

tensor([0.3043, 1.1612, 1.3948, 1.2869, 0.0000, 0.9418, 0.1786, 0.0000])

### Aufgabe 4

Erzeuge sowohl eine linear layer als auch eine ReLU activation function und forwade durch beide.

In [6]:
class Net(nn.Module): # Vererbung, daher Quelle in die Klammern
    
    def __init__(self):
        super().__init__()# gibt die Superklasse nn.module, außerdem rufen wir den Constuctor dieser Klasse auf!
        self.l1 = nn.Linear(8, 16)
        self.l2 = nn.Linear(16, 4)
        self.g = nn.ReLU()
        self.d = nn.Dropout(p=0.3, inplace=False)
        
    def forward(self, x):
        x = self.l1(x)# wir überschreiben x mit dem Ergebnis aus Layer1
        x = self.l2(x)
        x = self.g(x) # Pro Layer eine ReLU üblicherweise !
        x = self.d(x)
        return x
    
        
model = Net() # wir erzeugen ein Objekt der Klasse ! und packen es in eine variable (model)
model

Net(
  (l1): Linear(in_features=8, out_features=16, bias=True)
  (l2): Linear(in_features=16, out_features=4, bias=True)
  (g): ReLU()
  (d): Dropout(p=0.3, inplace=False)
)

In [11]:
# falsch, 1. zu viel 2. nicht geforwarded

m = nn.Linear(8, 16)
g = nn.ReLU()

# entweder
g(m(x))

tensor([0.0000, 0.3761, 0.0000, 0.8219, 0.3931, 0.0000, 0.4721, 0.1528, 0.0000,
        0.0000, 0.4504, 0.1243, 0.1528, 0.5380, 0.6837, 0.0535],
       grad_fn=<ReluBackward0>)

In [12]:
# oder

x_ = m(x)
x_ = g(x_)
x_

tensor([0.0000, 0.3761, 0.0000, 0.8219, 0.3931, 0.0000, 0.4721, 0.1528, 0.0000,
        0.0000, 0.4504, 0.1243, 0.1528, 0.5380, 0.6837, 0.0535],
       grad_fn=<ReluBackward0>)

### Aufgabe 5

Erzeugt wurde ein eigenes Module namens `CustomModule`.
Passe die `forward` Methode so an, dass dem x die Zahl $2$ addiert wird.

In [7]:
class CustomModule(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        x = x+2 # 1.Idee innerhalb der Methode, ERgebnis enthält zumindest immer 2 vor dem Komma! Rest war random, oder?
        return x
    
    
m = CustomModule()
m(x)

tensor([2.2439, 2.8835, 2.7882, 2.0388, 2.0718, 2.9681, 2.2125, 2.2506])

In [ ]:
# richtig