# Pytorch Komponenten

In [1]:
import torch
import torch.nn as nn

x = torch.rand(8)
x

tensor([0.9596, 0.8627, 0.8593, 0.8674, 0.1617, 0.7320, 0.5052, 0.6331])

### Beispiel

Erzeugen einer linear layer:

In [2]:
m = nn.Linear(8, 1)
m(x)

tensor([-0.0441], grad_fn=<AddBackward0>)

### Aufgabe 1

Erzeuge eine linear layer und führe ein forwarding wie im Beispiel durch mit: 
- in_features=8
- out_features=16

### Aufgabe 2

Erzeuge eine ReLU activation function und führe ein forwarding wie im Beispiel durch.

### Aufgabe 3

Erzeuge eine Dropout layer und führe ein forwarding wie im Beispiel durch.
- propability für den Dropout 30%

### Aufgabe 4

Erzeuge sowohl eine linear layer als auch eine ReLU activation function und forwade durch beide.

### Aufgabe 5

Erzeugt wurde ein eigenes Module namens `CustomModule`.
Passe die `forward` Methode so an, dass dem x die Zahl $2$ addiert wird.

In [3]:
class CustomModule(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x
    
    
m = CustomModule()
m(x)

tensor([0.9596, 0.8627, 0.8593, 0.8674, 0.1617, 0.7320, 0.5052, 0.6331])