In [1]:
import torch
import torch.nn as nn

### Aufgabe 1

Erzeuge eine Lineare Layer welche $12$ *inputs* aufnimmt und $32$ *outputs* ausgibt.

### Aufgabe 2

![nn](nn.svg)

Erzeuge die 5 Layer aus der Visualisierung.

### Aufgabe 3

*Forwarde* `x` durch die `fc` Komponente.

In [2]:
x = torch.rand(4, 16)
x

tensor([[0.4450, 0.4089, 0.0755, 0.7807, 0.4143, 0.2146, 0.8373, 0.1268, 0.0136,
         0.4790, 0.2335, 0.0071, 0.7716, 0.2109, 0.7855, 0.1463],
        [0.8696, 0.8227, 0.8106, 0.6446, 0.7850, 0.0047, 0.1836, 0.1032, 0.6831,
         0.5614, 0.3404, 0.8955, 0.2905, 0.0101, 0.0693, 0.4827],
        [0.2293, 0.8057, 0.9155, 0.2660, 0.7720, 0.4341, 0.5658, 0.2060, 0.1225,
         0.6583, 0.8975, 0.3266, 0.2081, 0.4750, 0.5740, 0.1383],
        [0.1773, 0.2759, 0.9447, 0.1017, 0.5066, 0.4841, 0.6016, 0.2817, 0.7317,
         0.7458, 0.4690, 0.1994, 0.3157, 0.0228, 0.2775, 0.3724]])

In [3]:
fc = nn.Sequential(
    nn.Linear(16, 32),
    nn.ReLU(),
    nn.Linear(32, 8),
    nn.ReLU(),
    nn.Linear(8, 3),
    nn.Softmax(dim=1)
)
fc

Sequential(
  (0): Linear(in_features=16, out_features=32, bias=True)
  (1): ReLU()
  (2): Linear(in_features=32, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=3, bias=True)
  (5): Softmax(dim=1)
)

### Aufgabe 4

Füge der Klasse das richtige *forwarding* hinzu. Bei dem Beispiel handelt es sich im *binary classification*.

In [4]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.l1 = nn.Linear(1000, 256)
        self.g1 = nn.ReLU()
        self.l2 = nn.Linear(256, 128)
        self.g2 = nn.ReLU()
        self.l3 = nn.Linear(128, 64)
        self.g3 = nn.Sigmoid()
        
    def forward(self, x):
        return x
    
    
net = Net()
net

Net(
  (l1): Linear(in_features=1000, out_features=256, bias=True)
  (g1): ReLU()
  (l2): Linear(in_features=256, out_features=128, bias=True)
  (g2): ReLU()
  (l3): Linear(in_features=128, out_features=64, bias=True)
  (g3): Sigmoid()
)

In [5]:
x = torch.rand(16, 1000)
x

tensor([[0.7991, 0.6659, 0.8573,  ..., 0.4483, 0.1901, 0.8580],
        [0.2952, 0.1638, 0.3493,  ..., 0.7371, 0.4326, 0.6241],
        [0.9853, 0.6143, 0.4866,  ..., 0.9416, 0.0266, 0.0820],
        ...,
        [0.9162, 0.3222, 0.8703,  ..., 0.4794, 0.9734, 0.2324],
        [0.5609, 0.8927, 0.1099,  ..., 0.4380, 0.0198, 0.8127],
        [0.9113, 0.4609, 0.2739,  ..., 0.2094, 0.9510, 0.3388]])

In [6]:
net(x)

tensor([[0.7991, 0.6659, 0.8573,  ..., 0.4483, 0.1901, 0.8580],
        [0.2952, 0.1638, 0.3493,  ..., 0.7371, 0.4326, 0.6241],
        [0.9853, 0.6143, 0.4866,  ..., 0.9416, 0.0266, 0.0820],
        ...,
        [0.9162, 0.3222, 0.8703,  ..., 0.4794, 0.9734, 0.2324],
        [0.5609, 0.8927, 0.1099,  ..., 0.4380, 0.0198, 0.8127],
        [0.9113, 0.4609, 0.2739,  ..., 0.2094, 0.9510, 0.3388]])

### Aufgabe 5

Beim folgendenen Modell wurde ein *high variance* Problem festgestellt. Füge $2$ *dropuput layers* an sinnvollen stellen hinzu.

In [7]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.fc = nn.Sequential(
            nn.Linear(16, 32),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Linear(32, 32),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        return self.fc(x)
    
    
net = Net()
net

Net(
  (fc): Sequential(
    (0): Linear(in_features=16, out_features=32, bias=True)
    (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=32, out_features=32, bias=True)
    (4): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=1, bias=True)
    (7): Sigmoid()
  )
)

In [8]:
x = torch.rand(4, 16)
x

tensor([[0.1958, 0.2737, 0.2721, 0.5563, 0.7919, 0.6845, 0.6496, 0.3550, 0.1769,
         0.2647, 0.5320, 0.9852, 0.7190, 0.2371, 0.7541, 0.3621],
        [0.9529, 0.0021, 0.3855, 0.1273, 0.8816, 0.1121, 0.8637, 0.3594, 0.8049,
         0.3972, 0.0342, 0.2374, 0.7328, 0.6447, 0.3527, 0.6209],
        [0.4340, 0.5443, 0.9948, 0.8759, 0.8823, 0.1066, 0.6169, 0.3867, 0.2467,
         0.9258, 0.0901, 0.3299, 0.8742, 0.4164, 0.4010, 0.4135],
        [0.1367, 0.7854, 0.2037, 0.3269, 0.7447, 0.4235, 0.7355, 0.0015, 0.7985,
         0.0970, 0.7527, 0.8798, 0.7116, 0.4390, 0.7374, 0.6481]])

In [9]:
net(x)

tensor([[0.3874],
        [0.4765],
        [0.3703],
        [0.3508]], grad_fn=<SigmoidBackward>)