# DATA SPLITTING UND PYTORCH DATASET

In [1]:
import numpy as np

from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split

### Aufgabe 1

Splitte die Daten `data` in `train_data` und `test_data` auf.
- Verhältnis von 70%/30%

In [2]:
data = np.random.rand(1000, 5)
data

array([[0.89523608, 0.83079998, 0.68958685, 0.33484928, 0.98291588],
       [0.61071463, 0.86215006, 0.68241968, 0.77754786, 0.1853804 ],
       [0.65510401, 0.07730025, 0.96193737, 0.40783759, 0.92799899],
       ...,
       [0.62452555, 0.54524746, 0.01999945, 0.22123216, 0.88096873],
       [0.19821873, 0.57447015, 0.10857586, 0.35795594, 0.70052476],
       [0.40205958, 0.597257  , 0.42366484, 0.52937891, 0.60357795]])

### Aufgabe 2

Splitte die Daten `x` und `y` in `x_train`, `x_test`, `y_train` und `y_test` auf.
- Verhältnis 95%/5%
- Daten sollen beim Split nicht zufällig gemischt werden

In [3]:
x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)

x, y

(array([[0.4525443 , 0.86022733, 0.9472101 , 0.88324378, 0.36523154],
        [0.12602064, 0.31025608, 0.15750222, 0.25107546, 0.23980016],
        [0.3380764 , 0.16325973, 0.35221485, 0.12985233, 0.2280188 ],
        ...,
        [0.47058547, 0.64633409, 0.16208311, 0.36740146, 0.4534694 ],
        [0.67199817, 0.08217424, 0.54801155, 0.49838277, 0.70869742],
        [0.12060902, 0.53116333, 0.9665804 , 0.40625086, 0.38359113]]),
 array([1, 1, 0, ..., 0, 0, 0]))

### Aufgabe 3

Splitte die Daten `data` in `train`, `dev` und `test` auf.
- Verhältnis 60%/20%/20%

In [4]:
data = np.random.rand(1000, 5)
data

array([[0.98767948, 0.11549822, 0.70540402, 0.05995446, 0.12603473],
       [0.91635618, 0.54423565, 0.48172452, 0.25745196, 0.46568374],
       [0.945342  , 0.93120862, 0.65457584, 0.08549202, 0.24020329],
       ...,
       [0.33374969, 0.89640415, 0.81891331, 0.3402954 , 0.85600966],
       [0.86275828, 0.57778322, 0.55138705, 0.87907428, 0.28779457],
       [0.92585241, 0.00454865, 0.88008818, 0.49230524, 0.88338014]])

### Aufgabe 4

Wir haben ein `Dataset` erzeugt. Jedoch gibt es bei `len(data)` nicht die richtige Länge (Anzahl der Elemente) zurück.
Behebe den Fehler.

In [5]:
x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)


class Data(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __len__(self):
        return 0
    
    
data = Data(x, y)
len(data)

0

### Aufgabe 5

Passe die Methode `__getitem__()` so an, dass sie den `x` und `y` Teil beim gegebenen Index `i` als `tuple` zurückgibt.

Beispiel:
```python
(array([0.45740839, 0.28119272, 0.5612359 , 0.78179437, 0.07652732]), 1)
```

In [6]:
x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)


class Data(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __getitem__(self, i):
        return 0
    

data = Data(x, y)
data[0]

0