# DATA SPLITTING UND PYTORCH DATASET

In [2]:
import numpy as np
import pandas as pd
import torch

from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split

### Aufgabe 1

Splitte die Daten `data` in `train_data` und `test_data` auf.
- Verhältnis von 70%/30%

In [3]:
# Längere Überlegung und Versuche: SKLearn-Data-Split will einen numpy-dataframe übergeben bekommen!
# Diesen muss ich also aus den Daten bilden! die Form der Daten passt (zweidimensional)

In [4]:
data = np.random.rand(1000, 5)

In [5]:
data

array([[0.83267073, 0.74702149, 0.56914635, 0.8411728 , 0.69645239],
       [0.82611318, 0.63207124, 0.9165846 , 0.92089508, 0.67136711],
       [0.30808429, 0.24690685, 0.92392668, 0.79440508, 0.51804712],
       ...,
       [0.75294363, 0.70357942, 0.19790992, 0.53776532, 0.26666421],
       [0.7206661 , 0.35189566, 0.79396687, 0.79029605, 0.79262557],
       [0.22987563, 0.07776973, 0.41260077, 0.31012527, 0.61439593]])

In [6]:
df = pd.DataFrame(data=data)# aud den zweidim Numpy Daten einen Dataframe bilden, um SKLeanr Split machen zu können !
df

0         1         2         3         4
0    0.832671  0.747021  0.569146  0.841173  0.696452
1    0.826113  0.632071  0.916585  0.920895  0.671367
2    0.308084  0.246907  0.923927  0.794405  0.518047
3    0.968414  0.467990  0.002175  0.163620  0.174387
4    0.401210  0.589401  0.869008  0.329988  0.562295
..        ...       ...       ...       ...       ...
995  0.043316  0.432197  0.240033  0.461701  0.116707
996  0.776171  0.172867  0.794609  0.013288  0.370132
997  0.752944  0.703579  0.197910  0.537765  0.266664
998  0.720666  0.351896  0.793967  0.790296  0.792626
999  0.229876  0.077770  0.412601  0.310125  0.614396

[1000 rows x 5 columns]

In [7]:
# Nun kann ich über den Parameter test_size=0.30 df übergeben und 30% Testdaten absplitten, es bleiben 70% Traindaten
# In diesem zusammenhang noch unklar: was genau tut der Parameter random_state=042? Klären wir später?

In [8]:
train_data, test_data = train_test_split(df, test_size=0.30, random_state=42)
train_data, test_data

(            0         1         2         3         4
 541  0.876108  0.480591  0.229952  0.706183  0.750458
 440  0.881301  0.217575  0.759872  0.699913  0.175919
 482  0.742994  0.496818  0.587285  0.509254  0.716307
 422  0.916896  0.691851  0.065028  0.290177  0.688857
 778  0.531375  0.592227  0.046583  0.098956  0.033163
 ..        ...       ...       ...       ...       ...
 106  0.706368  0.857731  0.871006  0.557343  0.145602
 270  0.590260  0.969887  0.760600  0.649741  0.576860
 860  0.864413  0.321628  0.367762  0.723900  0.086900
 435  0.791348  0.043786  0.795547  0.039074  0.391639
 102  0.587775  0.062448  0.691947  0.796169  0.100470
 
 [700 rows x 5 columns],
             0         1         2         3         4
 521  0.321380  0.394971  0.099972  0.804085  0.165798
 737  0.210410  0.203165  0.389690  0.586870  0.625863
 740  0.366983  0.861400  0.229307  0.378569  0.547450
 660  0.956691  0.697334  0.209201  0.532947  0.228746
 411  0.276785  0.790399  0.415504  0.

In [11]:
# alles richtig
# alternativ einfach ohne Umweg über pandas

train_data, test_data = train_test_split(data, test_size=0.3)
train_data.shape, test_data.shape

((700, 5), (300, 5))

### Aufgabe 2

Splitte die Daten `x` und `y` in `x_train`, `x_test`, `y_train` und `y_test` auf.
- Verhältnis 95%/5%
- Daten sollen beim Split nicht zufällig gemischt werden

In [14]:
x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)

x, y

(array([[0.10961867, 0.04824369, 0.41961594, 0.98184486, 0.05522578],
        [0.23831179, 0.2528238 , 0.72407389, 0.43389106, 0.53625981],
        [0.29395471, 0.57237927, 0.12469123, 0.29472794, 0.96122662],
        ...,
        [0.9210045 , 0.71687428, 0.56026608, 0.14456795, 0.673488  ],
        [0.19350292, 0.52441029, 0.14986502, 0.80393684, 0.0983729 ],
        [0.23893161, 0.76223892, 0.66975992, 0.05810729, 0.58145148]]),
 array([1, 0, 1, ..., 1, 0, 0]))

In [15]:
# Daten sollen beim Split nicht zufällig gemischt werden => meines Erachtens Random_state=None !

In [16]:
x_train, x_test = train_test_split(x, test_size=0.05, random_state=42) # direkter Versuch, da x in passender Ausgangsshape vorliegt
x_train.shape, x_test.shape

((9500, 5), (500, 5))

In [17]:
y_train, y_test = train_test_split(y, test_size=0.05, random_state=42) # direkter Versuch, da x in passender Ausgangsshape vorliegt
y_train.shape, y_test.shape

((9500,), (500,))

In [19]:
# Nun die randomisierung rausnehmen => shuffle=False, stratify=None Schwer zu überprüfen!

In [20]:
x_train, x_test = train_test_split(x, test_size=0.05,  shuffle=False, stratify=None)
x_train.shape, x_test.shape

((9500, 5), (500, 5))

In [21]:
y_train, y_test = train_test_split(y, test_size=0.05, shuffle=False, stratify=None)
y_train.shape, y_test.shape

((9500,), (500,))

In [23]:
# am Ende richtig
# alternativ und kürzer

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05, shuffle=False)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((9500, 5), (500, 5), (9500,), (500,))

### Aufgabe 3

Splitte die Daten `data` in `train`, `dev` und `test` auf.
- Verhältnis 60%/20%/20%

In [24]:
data = np.random.rand(1000, 5)
data

array([[0.11871409, 0.84089466, 0.09315831, 0.98052607, 0.91949041],
       [0.0864952 , 0.52936228, 0.61240211, 0.18032874, 0.19336573],
       [0.93368526, 0.02171262, 0.82014709, 0.3231843 , 0.74629226],
       ...,
       [0.93216163, 0.26255706, 0.2191875 , 0.48658815, 0.27021084],
       [0.39182445, 0.1563037 , 0.88776811, 0.11036809, 0.10580978],
       [0.52234142, 0.14266026, 0.62678278, 0.42322476, 0.7049603 ]])

In [25]:
# Wir bilden zunächst wieder einen pandas dataframe aus den Daten.

In [43]:
df = pd.DataFrame(data=data)# aud den zweidim Numpy Daten einen Dataframe bilden, um SKLeanr Split machen zu können !
df

0         1         2         3         4
0    0.030979  0.453657  0.561658  0.443964  0.985562
1    0.350198  0.957822  0.338817  0.491040  0.933789
2    0.675748  0.022404  0.747185  0.999391  0.346253
3    0.085321  0.382406  0.846828  0.216170  0.825235
4    0.710898  0.965902  0.698475  0.198980  0.937054
..        ...       ...       ...       ...       ...
995  0.998585  0.290623  0.231042  0.183385  0.992052
996  0.648724  0.970172  0.364782  0.870509  0.882351
997  0.631017  0.538946  0.936068  0.966754  0.290096
998  0.794143  0.814143  0.240370  0.329200  0.805828
999  0.696080  0.912125  0.692208  0.169917  0.491824

[1000 rows x 5 columns]

In [ ]:
# Vorgehen: zuerst einen train-test Split, dann einen train-dev Split !
# ein wenig trickie ist, erst df einzusetzen und dann train - sollte aber stimmen! (?)
# Geht sicher noch anders oder auf elefanterem Wege?

In [26]:
train, test = train_test_split(df, test_size=0.20, random_state=42) # Split für test set, 20 ab von df!
train.shape, test.shape

((800, 5), (200, 5))

In [27]:
train, dev = train_test_split(train, test_size=0.25, random_state=42) # dev für validation set, 25& ab von train!
train.shape, dev.shape

((600, 5), (200, 5))

In [28]:
# richtig
# alternative kürzer ohne Umweg mit pandas

train, test = train_test_split(data, test_size=0.2)
train, dev = train_test_split(train, test_size=0.25)
train.shape, dev.shape, test.shape

((600, 5), (200, 5), (200, 5))

### Aufgabe 4

Wir haben ein `Dataset` erzeugt. Jedoch gibt es bei `len(data)` nicht die richtige Länge (Anzahl der Elemente) zurück.
Behebe den Fehler.

In [29]:
x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)


class Data(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __len__(self):
        x = len(self.x)
        y = len(self.y)
        return x
        return y
     
    
    
data = Data(x, y)
len(data)

10000

In [ ]:
# Lange rumgetestet: so müsste ich die Länge von x und y ausgeben, die 5 ergeben sich ja nur in der Shape von x - länge ist immer 1000 bei x und y!

In [31]:
# richtig auch wenn das zweite return raus muss
# wir können davon ausgehen, dass x und y die gleich länge haben

x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)


class Data(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __len__(self):
        return len(self.x)
     
    
    
data = Data(x, y)
len(data)

10000

### Aufgabe 5

Passe die Methode `__getitem__()` so an, dass sie den `x` und `y` Teil beim gegebenen Index `i` als `tuple` zurückgibt.

Beispiel:
```python
(array([0.45740839, 0.28119272, 0.5612359 , 0.78179437, 0.07652732]), 1)
```

In [33]:
# Ein Tupel ist in einem Dict zuhause, oder? also in {} packen. Unsinn! Ich muss es aus der Poll prediction holen, dort was mit formatstring gemacht ! Tupel einfach so bilden als Paarwerte.

In [34]:
# Im Wesentlichen eine Problem zur Lösung der Fehlermeldung "'numpy.ndarray' object has no attribute iloc"
# Konvertieren in einen Pandas Dataframe, dann die gelernte Vorgehensweise - es sollte ein Tupel sein, welches herauskommt!
# Mir ist unklar, wieso der data rot einfärbt!

In [37]:
x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)


class Data(Dataset):
    def __init__(self, x, y):
        self.x = pd.DataFrame(x)
        self.y = pd.DataFrame(y)
    
    def __getitem__(self, i):
        return torch.tensor(self.x.iloc[i]).float(), torch.tensor(self.y.iloc[i]).float()
 

data = Data(x, y)
data[0]

(tensor([0.1884, 0.2731, 0.2837, 0.4419, 0.2146]), tensor([1.]))

In [38]:
x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)


class Data(Dataset):
    def __init__(self, x, y):
        self.x = pd.DataFrame(x)
        self.y = pd.DataFrame(y)
    
    def __getitem__(self, i):
        return np.array(self.x.iloc[i]).float(), np.array(self.y.iloc[i]).float() # das hier geht dann eben nicht!
 

data = Data(x, y)
data[0]

AttributeError: 'numpy.ndarray' object has no attribute 'float'

In [40]:
# falsch ist es nicht
# pandas und torch.tensor war nicht gefordert
# alternativ und viel kürzer

x = np.random.rand(10000, 5)
y = np.random.rand(10000).round().astype(int)


class Data(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __getitem__(self, i):
        return self.x[i], self.y[i]
    

data = Data(x, y)
data[0]

(array([0.08309881, 0.88687148, 0.11696594, 0.92359172, 0.67890401]), 1)